workMode = false
git.personal.name = "Sangeeth Sudheer"
git.personal.email = "git@sangeeth.dev"
git.personal.signingkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF6gTqNd8tw46xoS3kkiuhlYFfPTLR0bCiGxNr4VkN5k"
git.work.signingkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIroJ24rKYozGHbJNgNisX+tNv1ks34SO+PoyDSWCOu+"
